from collections import OrderedDict

APP_GROUPS = OrderedDict([
("system_auth_security", [
("APP-SYS-001","启动页","system","splash"),
("APP-SYS-002","系统维护页","system","status"),
("APP-SYS-003","App更新页","system","update"),
("APP-SYS-004","APK下载与安装引导","system","download"),
("APP-AUTH-001","登录页","account","auth_login"),
("APP-AUTH-002","注册页","account","auth_register"),
("APP-AUTH-003","找回密码页","account","form"),
("APP-AUTH-004","重置密码页","account","form"),
("APP-AUTH-005","协议查看页","account","article"),
("APP-SEC-001","图形安全验证码弹窗","security","captcha"),
("APP-SEC-002","邮箱安全验证弹窗","security","email_verify"),
("APP-SEC-003","赠送密码输入弹窗","security","pin"),
]),
("game", [
("APP-GAME-001","新手引导层","game","game_tutorial"),
("APP-GAME-002","矿场首页","game","game_home"),
("APP-GAME-003","矿机商店","game","miner_store"),
("APP-GAME-004","矿机仓库","game","warehouse"),
("APP-GAME-005","矿机图鉴","game","atlas"),
("APP-GAME-006","矿机详情","game","miner_detail"),
("APP-GAME-007","离线收益弹窗","game","offline_reward"),
("APP-GAME-008","新矿机解锁弹窗","game","unlock"),
("APP-GAME-009","任务中心","game","task_list"),
("APP-GAME-010","七日签到","game","signin"),
("APP-GAME-011","补给箱开启页","game","supply_box"),
("APP-GAME-012","排行榜","game","ranking"),
("APP-GAME-013","产出明细","game","ledger"),
("APP-GAME-014","矿机回收确认","game","confirm"),
("APP-GAME-015","棋盘格解锁弹窗","game","unlock_slot"),
("APP-GAME-016","仓库扩容确认","game","confirm"),
]),
("project", [
("APP-PROJ-001","项目首页","project","project_feed"),
("APP-PROJ-002","项目搜索","project","search"),
("APP-PROJ-003","发布或编辑项目","project","project_form"),
("APP-PROJ-004","项目图片管理","project","image_manager"),
("APP-PROJ-005","发布结果","project","result"),
("APP-PROJ-006","统一项目详情","project","project_detail"),
("APP-PROJ-007","联系方式与链接面板","project","contact_sheet"),
("APP-PROJ-008","项目举报","project","report_form"),
("APP-PROJ-009","我的项目","project","project_list"),
("APP-PROJ-010","项目管理详情","project","project_manage"),
("APP-PROJ-011","使用推广卡","project","promotion_apply"),
("APP-PROJ-012","推广服务记录","project","ledger"),
("APP-PROJ-013","我的收藏","project","project_list"),
("APP-PROJ-014","项目图片画廊","project","gallery"),
("APP-PROJ-015","项目分类选择器","project","category_picker"),
("APP-PROJ-016","浏览任务创建与预算确认","project","task_budget"),
]),
("mall_order_pay", [
("APP-MALL-001","商城首页","mall","mall_home"),
("APP-MALL-002","商品详情","mall","product_detail"),
("APP-MALL-003","订单确认","mall","order_confirm"),
("APP-MALL-004","虚拟背包","mall","inventory"),
("APP-PAY-001","原生收银台","payment","checkout"),
("APP-PAY-002","人工扫码支付","payment","manual_qr"),
("APP-PAY-003","支付结果和查单","payment","payment_result"),
("APP-ORDER-001","订单列表","order","order_list"),
("APP-ORDER-002","订单详情","order","order_detail"),
("APP-MEMBER-001","会员中心","membership","membership"),
]),
("discover_market", [
("APP-DISC-001","发现Tab容器","discover","discover"),
("APP-MARKET-001","积分集市","market","market"),
("APP-MARKET-002","发布或编辑求购单","market","market_form"),
("APP-MARKET-003","求购单详情","market","market_detail"),
("APP-MARKET-004","我的求购单","market","market_list"),
("APP-DISC-002","后续游戏入口页","discover","game_portal"),
]),
("wallet_invite_commission", [
("APP-WALLET-001","资产总览","wallet","wallet_home"),
("APP-WALLET-002","星矿值流水","wallet","ledger"),
("APP-WALLET-003","能源芯片流水","wallet","ledger"),
("APP-WALLET-004","账户余额流水","wallet","ledger"),
("APP-WALLET-005","赠送星矿值","wallet","transfer_form"),
("APP-WALLET-006","收款人确认","wallet","recipient_confirm"),
("APP-WALLET-007","赠送结果","wallet","result"),
("APP-WALLET-008","设置赠送密码","wallet","pin_setup"),
("APP-WALLET-009","修改或重置赠送密码","wallet","pin_setup"),
("APP-WALLET-010","兑换能源芯片","wallet","exchange"),
("APP-INVITE-001","邀请总览","referral","invite_home"),
("APP-INVITE-002","邀请海报","referral","invite_poster"),
("APP-INVITE-003","一级好友","referral","friend_list"),
("APP-INVITE-004","二级好友","referral","friend_list"),
("APP-INVITE-005","我的上级","referral","superior"),
("APP-COMM-001","积分提成明细","commission","ledger"),
("APP-COMM-002","消费佣金明细","commission","ledger"),
]),
("identity_withdraw", [
("APP-ID-001","实名入口与状态","identity","identity_status"),
("APP-ID-002","姓名身份证填写","identity","identity_form"),
("APP-ID-003","摄像头权限说明","identity","permission"),
("APP-ID-004","动作采集","identity","capture"),
("APP-ID-005","身份核验中","identity","verifying"),
("APP-ID-006","实名结果","identity","identity_result"),
("APP-WD-001","提现首页","withdrawal","withdraw_home"),
("APP-WD-002","绑定支付宝","withdrawal","alipay_bind"),
("APP-WD-003","提现确认","withdrawal","withdraw_confirm"),
("APP-WD-004","提现结果","withdrawal","withdraw_result"),
("APP-WD-005","提现记录","withdrawal","withdraw_list"),
("APP-WD-006","提现详情","withdrawal","withdraw_detail"),
]),
("me_message_settings", [
("APP-ME-001","我的","me","me_home"),
("APP-ME-002","编辑资料","me","profile_form"),
("APP-MSG-001","消息中心","message","message_list"),
("APP-MSG-002","消息详情","message","message_detail"),
("APP-SET-001","设置","settings","settings"),
("APP-SET-002","账号与安全","settings","settings"),
("APP-SET-003","登录设备","settings","device_list"),
("APP-SET-004","声音、震动和通知","settings","toggle_settings"),
("APP-SET-005","关于和版本更新","settings","about"),
("APP-SET-006","帮助中心","settings","help"),
("APP-SET-007","协议与隐私","settings","legal"),
("APP-SET-008","注销账号","settings","danger"),
("APP-SUPPORT-001","意见反馈","support","feedback"),
])
])

H5_PAGES = [
("H5-INVITE-001","邀请落地与邮箱注册","h5","invite_landing"),
("H5-PAY-001","支付返回页","h5","pay_return"),
("H5-DOWNLOAD-001","Android下载页","h5","download_landing"),
("H5-LEGAL-001","用户协议和隐私政策","h5","legal"),
("H5-PROJECT-001","项目外部分享预览页","h5","project_share"),
]

ADMIN_GROUPS = OrderedDict([
("auth_dashboard_user", [
("ADMIN-AUTH-001","后台登录","admin_auth","admin_login"),
("ADMIN-AUTH-002","后台安全验证码","admin_auth","admin_captcha"),
("ADMIN-AUTH-003","修改后台密码","admin_auth","admin_form"),
("ADMIN-DASH-001","运营总览","dashboard","dashboard"),
("ADMIN-USER-001","用户列表","user","admin_table"),
("ADMIN-USER-002","用户详情","user","admin_detail"),
("ADMIN-USER-003","用户状态与限制记录","user","admin_table"),
("ADMIN-USER-004","用户设备和会话","user","admin_table"),
("ADMIN-USER-005","用户关联业务时间线","user","admin_timeline"),
]),
("game", [
("ADMIN-GAME-001","游戏总配置","game","admin_config"),
("ADMIN-GAME-002","36级矿机列表","game","admin_cards"),
("ADMIN-GAME-003","矿机等级编辑","game","admin_form"),
("ADMIN-GAME-004","用户棋盘与仓库","game","admin_board"),
("ADMIN-GAME-005","合成和移动事件","game","admin_table"),
("ADMIN-GAME-006","矿机购买记录","game","admin_table"),
("ADMIN-GAME-007","产出规则和领取记录","game","admin_table"),
("ADMIN-GAME-008","商店价格配置","game","admin_table"),
("ADMIN-GAME-009","任务模板","game","admin_table"),
("ADMIN-GAME-010","用户任务进度","game","admin_table"),
("ADMIN-GAME-011","签到配置和记录","game","admin_table"),
("ADMIN-GAME-012","补给箱和掉落表","game","admin_table"),
("ADMIN-GAME-013","图鉴解锁记录","game","admin_table"),
("ADMIN-GAME-014","排行榜配置和快照","game","admin_table"),
("ADMIN-GAME-015","游戏资源版本","game","admin_table"),
]),
("asset_market", [
("ADMIN-ASSET-001","资产总览","asset","admin_dashboard"),
("ADMIN-ASSET-002","用户钱包账户","asset","admin_table"),
("ADMIN-ASSET-003","钱包交易","asset","admin_table"),
("ADMIN-ASSET-004","账本分录","asset","admin_table"),
("ADMIN-ASSET-005","人工资产调整","asset","admin_form"),
("ADMIN-ASSET-006","主副积分兑换记录","asset","admin_table"),
("ADMIN-ASSET-007","积分赠送记录","asset","admin_table"),
("ADMIN-ASSET-008","积分参考价格","asset","admin_chart"),
("ADMIN-MARKET-001","求购订单列表","market","admin_table"),
("ADMIN-MARKET-002","求购订单详情与审核","market","admin_detail"),
("ADMIN-MARKET-003","集市配置","market","admin_config"),
]),
("project", [
("ADMIN-PROJ-001","项目分类","project","admin_table"),
("ADMIN-PROJ-002","项目列表","project","admin_table"),
("ADMIN-PROJ-003","项目审核队列","project","admin_table"),
("ADMIN-PROJ-004","项目详情","project","admin_detail"),
("ADMIN-PROJ-005","项目举报","project","admin_table"),
("ADMIN-PROJ-006","推广服务配置","project","admin_config"),
("ADMIN-PROJ-007","推广服务使用记录","project","admin_table"),
("ADMIN-PROJ-008","浏览任务活动","project","admin_table"),
("ADMIN-PROJ-009","浏览任务会话和奖励","project","admin_table"),
("ADMIN-PROJ-010","项目运营统计","project","admin_dashboard"),
]),
("mall_member", [
("ADMIN-MALL-001","商品列表","mall","admin_table"),
("ADMIN-MALL-002","商品编辑","mall","admin_form"),
("ADMIN-MALL-003","虚拟商品订单","mall","admin_table"),
("ADMIN-MALL-004","订单详情","mall","admin_detail"),
("ADMIN-MALL-005","用户虚拟权益","mall","admin_table"),
("ADMIN-MALL-006","虚拟卡库存流水","mall","admin_table"),
("ADMIN-MEMBER-001","会员套餐","membership","admin_cards"),
("ADMIN-MEMBER-002","用户会员记录","membership","admin_table"),
("ADMIN-MEMBER-003","会员权益配置","membership","admin_config"),
]),
("referral_commission", [
("ADMIN-REF-001","邀请关系列表","referral","admin_table"),
("ADMIN-REF-002","邀请关系详情","referral","admin_detail"),
("ADMIN-REF-003","异常邀请关系","referral","admin_table"),
("ADMIN-COMM-001","积分提成规则","commission","admin_config"),
("ADMIN-COMM-002","积分提成记录","commission","admin_table"),
("ADMIN-COMM-003","消费佣金规则","commission","admin_config"),
("ADMIN-COMM-004","消费佣金记录","commission","admin_table"),
("ADMIN-COMM-005","佣金冲正和冻结","commission","admin_table"),
]),
("payment", [
("ADMIN-PAY-001","支付总览","payment","admin_dashboard"),
("ADMIN-PAY-002","支付方式配置","payment","admin_config"),
("ADMIN-PAY-003","XApay配置和健康检查","payment","admin_health"),
("ADMIN-PAY-004","人工扫码收款码池","payment","admin_cards"),
("ADMIN-PAY-005","支付订单","payment","admin_table"),
("ADMIN-PAY-006","支付订单详情","payment","admin_detail"),
("ADMIN-PAY-007","人工扫码审核","payment","admin_review"),
("ADMIN-PAY-008","支付回调和事件","payment","admin_timeline"),
("ADMIN-PAY-009","支付查单与对账","payment","admin_table"),
]),
("identity_withdrawal", [
("ADMIN-ID-001","实名配置","identity","admin_config"),
("ADMIN-ID-002","实名记录","identity","admin_table"),
("ADMIN-ID-003","实名详情","identity","admin_detail"),
("ADMIN-ID-004","第三方请求日志","identity","admin_table"),
("ADMIN-ID-005","人工复核","identity","admin_review"),
("ADMIN-WD-001","提现配置和档位","withdrawal","admin_config"),
("ADMIN-WD-002","提现订单","withdrawal","admin_table"),
("ADMIN-WD-003","提现详情和审核","withdrawal","admin_review"),
("ADMIN-WD-004","支付宝出款通道","withdrawal","admin_health"),
("ADMIN-WD-005","提现查单和对账","withdrawal","admin_table"),
]),
("storage_email_captcha", [
("ADMIN-STORAGE-001","R2配置和健康检查","storage","admin_health"),
("ADMIN-STORAGE-002","文件对象列表","storage","admin_table"),
("ADMIN-STORAGE-003","文件详情","storage","admin_detail"),
("ADMIN-STORAGE-004","孤立文件清理","storage","admin_table"),
("ADMIN-STORAGE-005","文件操作日志","storage","admin_table"),
("ADMIN-EMAIL-001","邮件服务配置","email","admin_config"),
("ADMIN-EMAIL-002","邮件模板","email","admin_table"),
("ADMIN-EMAIL-003","邮件发送记录","email","admin_table"),
("ADMIN-EMAIL-004","邮件统计和测试","email","admin_dashboard"),
("ADMIN-CAPTCHA-001","图形验证码配置","captcha","admin_config"),
("ADMIN-CAPTCHA-002","验证码统计和风险","captcha","admin_dashboard"),
]),
("content_app_system", [
("ADMIN-CONTENT-001","平台公告","content","admin_table"),
("ADMIN-CONTENT-002","站内消息","content","admin_table"),
("ADMIN-SUPPORT-001","用户反馈","support","admin_table"),
("ADMIN-APP-001","App版本列表","app_release","admin_table"),
("ADMIN-APP-002","App版本发布","app_release","admin_form"),
("ADMIN-SYS-001","运行配置中心","system","admin_config"),
("ADMIN-SYS-002","服务健康检查","system","admin_health"),
("ADMIN-SYS-003","定时任务和Worker","system","admin_table"),
("ADMIN-SYS-004","结构化日志查询","system","admin_table"),
("ADMIN-SYS-005","操作审计","system","admin_table"),
("ADMIN-RBAC-001","后台管理员","rbac","admin_table"),
("ADMIN-RBAC-002","角色管理","rbac","admin_table"),
("ADMIN-RBAC-003","权限管理","rbac","admin_tree"),
])
])

EXTRA_STATES = {
"APP-AUTH-001": ["ERROR", "SUBMITTING"],
"APP-AUTH-002": ["ERROR", "SUBMITTING"],
"APP-GAME-002": ["NEW_USER", "CLAIMABLE", "BOARD_FULL", "OFFLINE"],
"APP-PROJ-001": ["LOADING", "EMPTY", "ERROR"],
"APP-PROJ-006": ["TASK_RUNNING", "TASK_SUCCESS", "OFFLINE_BY_ADMIN"],
"APP-PAY-001": ["PROCESSING", "SUCCESS", "FAILURE", "EXPIRED"],
"APP-PAY-002": ["UPLOADING", "REVIEW_PENDING", "REJECTED"],
"APP-ID-004": ["PERMISSION_DENIED"],
"APP-ID-005": ["VERIFYING"],
"APP-ID-006": ["SUCCESS", "RECAPTURE", "FAILURE"],
"APP-WD-001": ["DISABLED"],
"APP-WD-004": ["PROCESSING", "SUCCESS", "FAILURE"],
"ADMIN-DASH-001": ["ERROR"],
"ADMIN-PAY-007": ["EMPTY"],
}


def flatten():
    app=[]
    for group, rows in APP_GROUPS.items():
        for pid,name,module,template in rows:
            app.append({"page_id":pid,"name_cn":name,"module":module,"template":template,"platform":"android","group":group})
    admin=[]
    for group, rows in ADMIN_GROUPS.items():
        for pid,name,module,template in rows:
            admin.append({"page_id":pid,"name_cn":name,"module":module,"template":template,"platform":"admin","group":group})
    h5=[{"page_id":pid,"name_cn":name,"module":module,"template":template,"platform":"h5","group":"h5"} for pid,name,module,template in H5_PAGES]
    return app,h5,admin

if __name__ == '__main__':
    a,h,ad=flatten()
    print(len(a),len(h),len(ad),len(a)+len(h)+len(ad))
    print('extra',sum(len(v) for v in EXTRA_STATES.values()),'total renders',len(a)+len(h)+len(ad)+sum(len(v) for v in EXTRA_STATES.values()))
