-- 星矿纪元 V1.1.0 核心数据库结构
-- PostgreSQL 16+；所有金额和积分使用NUMERIC，禁止浮点。
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), uid bigint NOT NULL UNIQUE CHECK(uid>=2026),
  status varchar(32) NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE SEQUENCE IF NOT EXISTS user_uid_seq START 2026;
CREATE TABLE user_profiles (user_id uuid PRIMARY KEY REFERENCES users(id), nickname varchar(40) NOT NULL, avatar_file_id uuid, identity_status varchar(32) NOT NULL DEFAULT 'UNVERIFIED', membership_expires_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE user_identifiers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), type varchar(20) NOT NULL, normalized_value varchar(255) NOT NULL, verified_at timestamptz, UNIQUE(type,normalized_value));
CREATE TABLE password_credentials (user_id uuid PRIMARY KEY REFERENCES users(id), password_hash text NOT NULL, algorithm varchar(20) NOT NULL DEFAULT 'argon2id', updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE user_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), refresh_token_hash text NOT NULL UNIQUE, device_id varchar(128), expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE email_verification_codes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), normalized_email varchar(255) NOT NULL, purpose varchar(32) NOT NULL, code_hash text NOT NULL, expires_at timestamptz NOT NULL, attempts int NOT NULL DEFAULT 0, consumed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE referral_relations (user_id uuid PRIMARY KEY REFERENCES users(id), parent_user_id uuid REFERENCES users(id), bound_at timestamptz NOT NULL DEFAULT now(), CHECK(user_id IS DISTINCT FROM parent_user_id));
CREATE TABLE referral_closure (ancestor_user_id uuid NOT NULL REFERENCES users(id), descendant_user_id uuid NOT NULL REFERENCES users(id), depth smallint NOT NULL CHECK(depth IN (1,2)), PRIMARY KEY(ancestor_user_id,descendant_user_id,depth));
CREATE TABLE membership_plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(40) UNIQUE NOT NULL, name varchar(80) NOT NULL, duration_days int NOT NULL, cash_price numeric(18,2) NOT NULL, promotion_discount numeric(8,6) NOT NULL DEFAULT .5, enabled boolean NOT NULL DEFAULT true);
CREATE TABLE user_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), plan_id uuid NOT NULL REFERENCES membership_plans(id), starts_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, source_order_id uuid, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE miner_level_configs (level smallint PRIMARY KEY CHECK(level BETWEEN 1 AND 36), miner_id varchar(20) UNIQUE NOT NULL, name varchar(80) NOT NULL, production_per_hour numeric(38,8) NOT NULL CHECK(production_per_hour>=0), base_price numeric(38,8) NOT NULL CHECK(base_price>=0), direct_purchase_enabled boolean NOT NULL DEFAULT true, asset_version varchar(40) NOT NULL, enabled boolean NOT NULL DEFAULT true);
CREATE TABLE user_game_profiles (user_id uuid PRIMARY KEY REFERENCES users(id), board_version bigint NOT NULL DEFAULT 1, highest_level smallint NOT NULL DEFAULT 1, warehouse_capacity int NOT NULL DEFAULT 8, unclaimed_amount numeric(38,8) NOT NULL DEFAULT 0, last_settled_at timestamptz NOT NULL DEFAULT now(), total_produced numeric(38,8) NOT NULL DEFAULT 0, total_claimed numeric(38,8) NOT NULL DEFAULT 0);
CREATE TABLE user_miners (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), level smallint NOT NULL REFERENCES miner_level_configs(level), state varchar(32) NOT NULL, locked boolean NOT NULL DEFAULT false, source_type varchar(32) NOT NULL, source_business_id varchar(80), created_at timestamptz NOT NULL DEFAULT now(), consumed_at timestamptz);
CREATE TABLE user_board_slots (user_id uuid NOT NULL REFERENCES users(id), slot_no smallint NOT NULL CHECK(slot_no BETWEEN 1 AND 16), unlocked boolean NOT NULL DEFAULT false, miner_id uuid UNIQUE REFERENCES user_miners(id), PRIMARY KEY(user_id,slot_no));
CREATE TABLE user_warehouse_slots (user_id uuid NOT NULL REFERENCES users(id), slot_no smallint NOT NULL CHECK(slot_no BETWEEN 1 AND 24), miner_id uuid UNIQUE REFERENCES user_miners(id), PRIMARY KEY(user_id,slot_no));
CREATE TABLE miner_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), event_type varchar(32) NOT NULL, source_miner_id uuid, target_miner_id uuid, result_miner_id uuid, board_version_before bigint, board_version_after bigint, idempotency_key uuid NOT NULL UNIQUE, payload jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE production_claims (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), amount numeric(38,8) NOT NULL CHECK(amount>=0), idempotency_key uuid NOT NULL UNIQUE, wallet_transaction_id uuid, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE wallet_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), asset_type varchar(32) NOT NULL, available_balance numeric(38,8) NOT NULL DEFAULT 0 CHECK(available_balance>=0), frozen_balance numeric(38,8) NOT NULL DEFAULT 0 CHECK(frozen_balance>=0), version bigint NOT NULL DEFAULT 1, UNIQUE(user_id,asset_type));
CREATE TABLE wallet_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_type varchar(40) NOT NULL, business_id varchar(100) NOT NULL, idempotency_key uuid NOT NULL UNIQUE, status varchar(24) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(business_type,business_id));
CREATE TABLE wallet_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), transaction_id uuid NOT NULL REFERENCES wallet_transactions(id), account_id uuid NOT NULL REFERENCES wallet_accounts(id), direction varchar(8) NOT NULL CHECK(direction IN ('DEBIT','CREDIT')), amount numeric(38,8) NOT NULL CHECK(amount>0), balance_before numeric(38,8) NOT NULL, balance_after numeric(38,8) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE point_transfer_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), transfer_no varchar(64) UNIQUE NOT NULL, sender_user_id uuid NOT NULL REFERENCES users(id), recipient_user_id uuid NOT NULL REFERENCES users(id), star_amount numeric(38,8) NOT NULL CHECK(star_amount>0), energy_fee numeric(38,8) NOT NULL CHECK(energy_fee>=0), status varchar(24) NOT NULL, idempotency_key uuid NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE point_price_history (price_date date PRIMARY KEY, reference_price numeric(18,8) NOT NULL CHECK(reference_price>0), daily_rate numeric(8,6) NOT NULL DEFAULT .01, source varchar(32) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE project_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(40) NOT NULL, sort_order int NOT NULL DEFAULT 0, is_system_default boolean NOT NULL DEFAULT false, enabled boolean NOT NULL DEFAULT true);
CREATE TABLE projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_user_id uuid NOT NULL REFERENCES users(id), category_id uuid REFERENCES project_categories(id), title varchar(80) NOT NULL, summary varchar(240) NOT NULL, content text NOT NULL, link_url text, status varchar(32) NOT NULL, published_at timestamptz, last_refresh_at timestamptz, refresh_priority_until timestamptz, headline_until timestamptz, pin_until timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE project_images (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, file_id uuid NOT NULL, sort_order smallint NOT NULL, UNIQUE(project_id,sort_order), CHECK(sort_order BETWEEN 1 AND 8));
CREATE TABLE project_favorites (user_id uuid NOT NULL REFERENCES users(id), project_id uuid NOT NULL REFERENCES projects(id), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,project_id));
CREATE TABLE project_task_campaigns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), owner_user_id uuid NOT NULL REFERENCES users(id), reward_per_user numeric(38,8) NOT NULL CHECK(reward_per_user>0), target_users int NOT NULL CHECK(target_users>0), completed_users int NOT NULL DEFAULT 0, required_seconds int NOT NULL CHECK(required_seconds BETWEEN 5 AND 600), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, status varchar(32) NOT NULL);
CREATE TABLE project_task_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid NOT NULL REFERENCES project_task_campaigns(id), user_id uuid NOT NULL REFERENCES users(id), accumulated_seconds int NOT NULL DEFAULT 0, status varchar(24) NOT NULL, last_heartbeat_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(campaign_id,user_id));
CREATE TABLE project_task_rewards (campaign_id uuid NOT NULL REFERENCES project_task_campaigns(id), user_id uuid NOT NULL REFERENCES users(id), wallet_transaction_id uuid NOT NULL, amount numeric(38,8) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(campaign_id,user_id));

CREATE TABLE mall_products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_type varchar(40) NOT NULL, name varchar(100) NOT NULL, cash_price numeric(18,2), star_price numeric(38,8), energy_price numeric(38,8), stock bigint, handler_code varchar(80) NOT NULL, enabled boolean NOT NULL DEFAULT true, config jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), out_trade_no varchar(64) UNIQUE NOT NULL, user_id uuid NOT NULL REFERENCES users(id), order_type varchar(40) NOT NULL, status varchar(32) NOT NULL, currency varchar(16) NOT NULL, original_amount numeric(38,8) NOT NULL, discount_amount numeric(38,8) NOT NULL DEFAULT 0, payable_amount numeric(38,8) NOT NULL, expires_at timestamptz, idempotency_key uuid NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id), product_id uuid REFERENCES mall_products(id), item_type varchar(40) NOT NULL, quantity int NOT NULL CHECK(quantity>0), unit_price numeric(38,8) NOT NULL, benefit_snapshot jsonb NOT NULL);
CREATE TABLE payment_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL UNIQUE REFERENCES orders(id), payment_method varchar(32), provider varchar(32), provider_trade_no varchar(128) UNIQUE, status varchar(32) NOT NULL, paid_amount numeric(18,2), paid_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE payment_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), payment_order_id uuid NOT NULL REFERENCES payment_orders(id), event_type varchar(40) NOT NULL, provider_event_id varchar(128), payload_hash varchar(128), verified boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider_event_id));
CREATE TABLE payment_settlement_records (order_id uuid PRIMARY KEY REFERENCES orders(id), settled_at timestamptz NOT NULL, result jsonb NOT NULL);
CREATE TABLE manual_payment_submissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id), version int NOT NULL, proof_file_id uuid NOT NULL, status varchar(32) NOT NULL, submitted_at timestamptz NOT NULL DEFAULT now(), UNIQUE(order_id,version));

CREATE TABLE commission_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_business_type varchar(40) NOT NULL, source_business_id varchar(100) NOT NULL, beneficiary_user_id uuid NOT NULL REFERENCES users(id), source_user_id uuid NOT NULL REFERENCES users(id), commission_type varchar(20) NOT NULL, level smallint NOT NULL CHECK(level IN (1,2)), rate numeric(8,6) NOT NULL, amount numeric(38,8) NOT NULL, status varchar(24) NOT NULL, wallet_transaction_id uuid, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(source_business_id,beneficiary_user_id,commission_type,level));
CREATE TABLE identity_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), status varchar(32) NOT NULL, real_name_ciphertext text, id_number_ciphertext text, id_number_hash varchar(128), actions jsonb NOT NULL, provider_result_code varchar(20), created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE identity_captures (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES identity_sessions(id), photo_file_id uuid, video_file_id uuid, status varchar(24) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE identity_bindings (user_id uuid PRIMARY KEY REFERENCES users(id), id_number_hash varchar(128) NOT NULL UNIQUE, verified_at timestamptz NOT NULL);
CREATE TABLE withdrawal_tiers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), amount numeric(18,2) NOT NULL UNIQUE, max_per_day int NOT NULL, max_total int, fee_amount numeric(18,2) NOT NULL DEFAULT 0, enabled boolean NOT NULL DEFAULT true);
CREATE TABLE user_payment_accounts (user_id uuid PRIMARY KEY REFERENCES users(id), account_type varchar(20) NOT NULL DEFAULT 'ALIPAY', real_name_ciphertext text NOT NULL, account_ciphertext text NOT NULL, account_hash varchar(128) NOT NULL, verified_at timestamptz NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE withdrawal_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), withdrawal_no varchar(64) UNIQUE NOT NULL, user_id uuid NOT NULL REFERENCES users(id), tier_id uuid NOT NULL REFERENCES withdrawal_tiers(id), amount numeric(18,2) NOT NULL, fee_amount numeric(18,2) NOT NULL, status varchar(32) NOT NULL, provider_order_no varchar(128) UNIQUE, idempotency_key uuid NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);

CREATE TABLE file_objects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), bucket varchar(120) NOT NULL, object_key text NOT NULL UNIQUE, purpose varchar(40) NOT NULL, visibility varchar(20) NOT NULL, mime_type varchar(120), size_bytes bigint, sha256 varchar(64), status varchar(24) NOT NULL, owner_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), delete_after timestamptz);
CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), type varchar(40) NOT NULL, title varchar(120) NOT NULL, body text NOT NULL, business_type varchar(40), business_id varchar(100), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notification_reads (notification_id uuid NOT NULL REFERENCES notifications(id), user_id uuid NOT NULL REFERENCES users(id), read_at timestamptz NOT NULL, PRIMARY KEY(notification_id,user_id));
CREATE TABLE runtime_configs (config_key varchar(160) PRIMARY KEY, value_json jsonb NOT NULL, value_type varchar(24) NOT NULL, sensitive boolean NOT NULL DEFAULT false, updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE outbox_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aggregate_type varchar(40) NOT NULL, aggregate_id varchar(100) NOT NULL, event_type varchar(80) NOT NULL, payload jsonb NOT NULL, status varchar(20) NOT NULL DEFAULT 'PENDING', attempts int NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now());
